#!/bin/bash

# Runs all executable the $hookname.d/* hooks and exits after,
# if any of them was not successful.
#
# Based on
# http://osdir.com/ml/git/2009-01/msg00308.html

data=$(cat)
exitcodes=()
hookname=`basename $0`
hookdir=`dirname $0`

# Run each hook, passing through STDIN and storing the exit code.
# We don't want to bail at the first failure, as the user might
# then bypass the hooks without knowing about additional issues.

for hook in $hookdir/$hookname.d/*; do
	test -x "$hook" || continue
	echo "$data" | "$hook" "$@"
	exitcodes+=($?)
done

if [[ -x "$(pwd)/.git/hooks/$hookname" ]]; then
	echo "$data" | "$(pwd)/.git/hooks/$hookname" "$@"
	exitcodes+=($?)
fi

for code in "${exitcodes[@]}"; do
	if [[ "$code" -ne "0" ]]; then
		echo
		echo "To commit anyway, use --no-verify"
		echo "  But we all know you shouldn't."

		exit "$code"
	fi
done
