#!/usr/bin/env bash

TOP_LEVEL="$(/usr/bin/env git rev-parse --show-toplevel)"

if [[ -z "$TOP_LEVEL" ]]; then
	exit 1
fi

HOOKS_DIRECTORY="${TOP_LEVEL}/.git/hooks"

if [[ -d "$HOOKS_DIRECTORY" ]]; then
	read -p "Are you sure you want to delete the hooks? ${HOOKS_DIRECTORY} [y/N] " -n 1 -r
	echo

	if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
		exit 1
	fi

	rm -r -- "${HOOKS_DIRECTORY}"
fi

git init
