#!/usr/bin/env bash

# Age of a file before it's deleted from the "recycle" folders.
#   Positive numbers need to be prefixed with +, if you want to delete them right away use "0"
DELETE_OLDER_THAN_DAYS="+7"

RECYCLE_ROOT_DIRECTORY="./"
RECYCLE_DIRECTORY=".recycle"

VERBOSE=false

# Find all directories within the $RECYCLE_ROOT_DIRECTORY, named $RECYCLE_DIRECTORY.
# Do not follow symbolic links ( -P )
RECYCLABLE_DIRECTORIES=`find -P "$RECYCLE_ROOT_DIRECTORY" -type d -name "$RECYCLE_DIRECTORY"`

[ "$VERBOSE" = true ] && echo "Running cleanup for recycle directories older than $DELETE_OLDER_THAN_DAYS days"

for directory in $RECYCLABLE_DIRECTORIES; do
	[ "$VERBOSE" = true ] && echo "Cleaning recycle directory $directory"

	# Find all files / symbolic links within the found recycle directory which
	# are older than $DELETE_OLDER_THAN_DAYS ( -ctime ) and delete them. 
	# Do not follow symbolic links ( -P ).
	find -P "$directory" -ctime "$DELETE_OLDER_THAN_DAYS" \( -type f -o -type l \) -delete

	# Find all directories within the found recycle directory which are empty
	# and remove them.  Do not follow symbolic links ( -P ) and do not delete the
	# current directory ( -mindepth 1 ) - deepest first ( -depth )
	find -P "$directory" -depth -mindepth 1 -type d -empty -delete

	# If the recycle directory is empty then remove it
	if [ -z "$(ls -A $directory)" ]; then
		[ "$VERBOSE" = true ] && echo "Removing empty recycle directory $directory"

		rmdir "$directory"
	fi
done
