#!/bin/bash

table=$1
file=$2

if [[ $# != 2 ]]; then
	echo 'invalid paramaters'
	echo 'Usage: tsql-import <import table> <import file>'

	exit 1
fi

read -r -p "Server: " server
read -r -p "Username: " username
read -r -p "Password: " -s password

freebcp "$table" in "$file" -c -S "$server" -U "$username" -P "$password"
