#!/bin/sh

if [[ $1 == "create" ]]; then
	shift
	exec hub pull-request $@
elif [[ $1 == "list" ]]; then
	shift
	exec hub pr list $@
elif [[ $1 == "show" ]]; then
	shift
	exec hub issue show $@

else
	exec hub pr list $@
fi
