#!/bin/bash

START_TS="$(date -d'last-monday 0' +%s)"
START_DATE="$(date -d'last-monday 0' +%Y-%m-%d)"

END_TS="$(date -d'monday 23:59:59' +%s)"
END_DATE="$(date -d'monday 23:59:59' +%Y-%m-%d)"

MERGED_PRS=$(hub pr list -s merged -L 100 -o merged --format '%mt %i %au%n' | awk -v start="${START_TS}" -v end="${END_TS}" '$1 >= start && $1 <= end { print $0; }')
MERGED_PRS_COUNT=$(echo "$MERGED_PRS" | wc -l)
MERGED_PRS_NODEPS_COUNT=$(echo "$MERGED_PRS" | awk -v dependabot="dependabot[bot]" '$3 != dependabot { print $0 }' |  wc -l)

ISSUES_OPENED=$(hub issue --state open --sort opened --limit 100 --format '%ct %I %t%n' | awk -v start="${START_TS}" -v end="${END_TS}" '$1 >= start && $1 <= end { print $0; }')
ISSUES_OPENED_COUNT=$(echo "$ISSUES_OPENED" | wc -l)

ISSUES_CLOSED=$(hub issue --state closed  --limit 100 --format '%ut %I %t%n' | awk -v start="${START_TS}" -v end="${END_TS}" '$1 >= start && $1 <= end { print $0; }')
ISSUES_CLOSED_COUNT=$(echo "$ISSUES_CLOSED" | wc -l)

RELEASES=$(hub release --format '%pt%n' | awk -v start="${START_TS}" -v end="${END_TS}" '$1 >= start && $1 <= end { print $0; }')
RELEASES_DAYS_COUNT=$(echo "$RELEASES" | awk '{print strftime("%Y-%m-%d", $1);}' | sort | uniq | wc -l)

echo "$START_DATE -> $END_DATE"

echo "RELEASE DAYS:       $RELEASES_DAYS_COUNT"
echo "PR MERGED:          $MERGED_PRS_COUNT"
echo "PR MERGED (nodep):  $MERGED_PRS_NODEPS_COUNT"
echo "ISSUE OPENED:       $ISSUES_OPENED_COUNT"
echo "ISSUE CLOSED:       $ISSUES_CLOSED_COUNT"
