#!/usr/bin/env sh

die() {
	echo $1

	exit 1
}

command_exists() {
	command -v "$1" &> /dev/null

	RETURN_VALUE="$?"

	if [[ "$RETURN_VALUE" == "0" ]]; then
		return 0
	else
		return 1
	fi
}

execute_wine_command () {
	/usr/bin/env \
		WINEARCH="win32" \
		WINEPREFIX="$HOME/.wine32_ss13/" \
		WINEDEBUG="-all" \
		wine "$@"
}

execute_winetricks_command () {
	/usr/bin/env \
		WINEARCH="win32" \
		WINEPREFIX="$HOME/.wine32_ss13/" \
		WINEDEBUG="-all" \
		winetricks "$@"
}

command_exists "wine" || die "wine is not installed"
command_exists "winetricks" || die "winetricks is not installed"
command_exists "wget" || die "wget is not installed"

if [[ "$1" == "--help" || "$1" == "-h" ]]; then

	echo "usage: ss13 [other.exe]"
	echo "       ss13 setup [--beta]"
	echo "       ss13 cfg"

elif [[ "$1" == "setup" ]]; then
	if [[ "$2" == "--beta" ]]; then
		echo "Setting up beta byond.."
	fi

	execute_wine_command "wineboot"

	execute_winetricks_command wsh56 wsh57 jscript mfc42 vcrun2013
	execute_winetricks_command ie7
	execute_winetricks_command ie8

	TMP_EXE_FILE="$(mktemp)"

	BUILD_REGEX='.\+href="\([^"]\+_byond.exe\)".\+'

	if [[ "$2" == "--beta" ]]; then
		BUILD_EXE=$(wget -o /dev/null -O - http://www.byond.com/download/ | grep -Po 'build/[^"]+_byond.exe' | tail -n1)
	else
		BUILD_EXE=build/LATEST/$(wget -o /dev/null -O - http://www.byond.com/download/build/LATEST/ | grep -i "$BUILD_REGEX" | sed "s/$BUILD_REGEX/\1/gi" | tail -n1)
	fi


	echo "Downloading $BUILD_EXE..."

	wget -O $TMP_EXE_FILE "http://www.byond.com/download/$BUILD_EXE"

	execute_wine_command $TMP_EXE_FILE

	rm $TMP_EXE_FILE

elif [[ "$1" == "winecfg" || "$1" == "cfg" ]]; then

	execute_wine_command "winecfg"

elif [[ $# -gt 0 ]]; then

	execute_wine_command $@

else

	execute_wine_command "C:/Program Files/Byond/bin/byond.exe"

fi
