#!/bin/bash

cat "$1" | \
awk 'f>1;/---/{f+=1}' | \
awk '{ $0=tolower($0); gsub(/(^[^a-z]+)|([^a-z]+$)/, ""); print; }' RS=' ' | \
grep -vP '^$' | \
grep -vP '^\s*(an|a|the|of)\s*$' | \
sort | uniq -c | sort -g -r

